[package]
name = "template"
version = "0.1.0"
edition = "2024"

[dependencies]
poem = { version = "3.0", features = ["tokio"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"