[package]
name = "template"
version = "0.1.0"
edition = "2024"

[dependencies]
tide = "0.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
async-std = { version = "1.12", features = ["attributes"] }